### ISSUE TITLE
Problem changing tap

### ISSUE THREAD

**Issue by DHKaplan** [apparition47/homebrew-tap#2]
% brew untap apparition47/tap
Error: Refusing to untap apparition47/tap because it contains the following installed formulae or casks:
mailtrackerblocker
%

Running on macOS 11.2.3

**Comment by apparition47** [comment]
Try:

```bash
brew uninstall mailtrackerblocker
brew untap apparition47/tap
brew install mailtrackerblocker
```

This should switch your install over to the offical Cask repo.

**Comment by DHKaplan** [comment]
Not yet it doesn't:

% brew uninstall mailtrackerblocker

==> Uninstalling Cask mailtrackerblocker
==> Uninstalling packages:
com.onefatgiraffe.mailtrackerblocker
Password:
find: /private/tmp/MailTrackerBlocker-Installation-Temp: No such file or directory
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/bash -c set\ -euo\ pipefail'
''
'for\ path\ in\ \"\$\{@\}\"\;\ do'
'\ \ if\ \[\[\ -e\ \"\$\{path\}/.DS_Store\"\ \]\]\;\ then'
'\ \ \ \ /bin/rm\ -f\ \"\$\{path\}/.DS_Store\"'
'\ \ fi'
''
'\ \ \#\ Some\ packages\ leave\ broken\ symlinks\ around\;\ we\ clean\ them\ out\ before'
'\ \ \#\ attempting\ to\ \`rmdir\`\ to\ prevent\ extra\ cruft\ from\ accumulating.'
'\ \ /usr/bin/find\ \"\$\{path\}\"\ -mindepth\ 1\ -maxdepth\ 1\ -type\ l\ \!\ -exec\ /bin/test\ -e\ \{\}\ \\\;\ -delete'
''
'\ \ if\ \[\[\ -L\ \"\$\{path\}\"\ \]\]\;\ then'
'\ \ \ \ \#\ Delete\ directory\ symlink.'
'\ \ \ \ /bin/rm\ \"\$\{path\}\"'
'\ \ elif\ \[\[\ -d\ \"\$\{path\}\"\ \]\]\;\ then'
'\ \ \ \ \#\ Delete\ directory\ if\ empty.'
'\ \ \ \ /usr/bin/find\ \"\$\{path\}\"\ -maxdepth\ 0\ -type\ d\ -empty\ -exec\ /bin/rmdir\ \{\}\ \\\;'
'\ \ else'
'\ \ \ \ \#\ Try\ \`rmdir\`\ anyways\ to\ show\ a\ proper\ error.'
'\ \ \ \ /bin/rmdir\ \"\$\{path\}\"'
'\ \ fi'
'done'
' --` exited with 1. Here's the output:
find: /private/tmp/MailTrackerBlocker-Installation-Temp: No such file or directory

**Comment by apparition47** [comment]
There's a problem with pre-0.3.22 and Homebrew that you'll have to workaround by:

mkdir /private/tmp/MailTrackerBlocker-Installation-Temp

Then running the uninstall command again

**Comment by DHKaplan** [comment]
🍺  mailtrackerblocker was successfully installed!

Thanks!!

**Comment by apparition47** [comment]
Appreciate your feedback, thanks!
